config/routes.rb
Rails.application.routes.draw do

  namespace :wild_apricot do
    post 'webhook', to: "webhook#create"
  end

  resources :events, only: [:index, :show, :update]
  resources :waitlist, only: [:index]
  resources :waitlist_registrations, only: [:index, :create, :new]

  resources :users, only: [:index, :show, :edit, :update] do
    resource :onboarding
    resources :fields, :show, controller: "user_fields"
    patch 'sync'
  end
  resource :batch_update_tool do
    get 'search'
    get 'contact'
  end

  get 'formbot/:event', to: 'formbot#redirect', as: :formbot
  get 'signoffs', to: 'signoffs#index'

  # Admin Section
  get 'admin', to: 'admin/welcome#show'
  namespace :admin do
    resource :sync
    resources :fields, only: [:index, :show]
    resources :users, only: [:index, :show] do
      resources :fields, :show, controller: "user_fields"
    end
  end

  # Defines the root path route ("/")
  root 'welcome#index'

  # Routes for OmniAuth
  post '/auth/:provider/callback', to: 'sessions#create'
  get '/callback/:provider', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: :logout
end

app/models/field.rb
class Field < ApplicationRecord
  has_many :field_allowed_values, -> { order(position: :asc) }, dependent: :destroy
  has_many :field_user_values, dependent: :destroy

  # Boy do I hate using a display name string for a scope
  scope :signoffs, -> { find_by(field_name: "NL Signoffs and Categories") }
  scope :permissions, -> { find_by(field_name: "NL Signoff Permissions") }
  scope :reason_for_free_access, -> { find_by(field_name: "Reason for free access") }
  scope :badge_number, -> { find_by(field_name: "Badge Number") }
  scope :door_access_group, -> { find_by(field_name: "Door Access Group") }
end

app/controllers/admin/fields_controller.rb
class Admin::FieldsController < Admin::BaseController
  def index
    @fields = Field.all.order(order: :desc)
  end

  def show
    @field = Field.find(params[:id])
  end
end

app/helpers/fields_helper.rb
module FieldsHelper
  def print_field_user_values(values)
    Array(print_field_user_value(values))
  end

  def print_field_user_value(values)
    return if values.empty?

    field = values.first.field

    case field.field_type
    when "Boolean"
      (values.first.value == "t").to_s
    when "Number"
      values.first.value
    when "DateTime"
      values.first.value
    when "String"
      values.first.value

      # Why does "choice" find the field allowed value by value, but
      # "MultipleChoice" find the field allowed value by uid? Good question.
      # The WAAPI returns fields for the contact no value when it is multiple
      # choice, instead they give the ID. That ID appens to map to the right
      # thing.
      #
      # When it is a "Choice" field then they like to stuff the value of that
      # AllowedValue.
      #
      # Examples. Here is a Choice:
      #
      # {
      #   "FieldName": "Membership status",
      #   "Value": {
      #     "Id":1,
      #     "Label":"Active",
      #     "Value":"Active",
      #     "SelectedByDefault":false,
      #     "Position":0
      #   },
      #   "SystemCode":"Status"
      # }
      #
      #
      #  {
      #    "FieldName":"NL Signoff Permissions",
      #    "Value":[
      #       {
      #          "Id":14917545,
      #          "Label":"WW"
      #       }
      #    ],
      #    "SystemCode":"custom-13082555"
      # }
      #

    when "Choice"
      values.map do |v|
        v.field.field_allowed_values.find_by(value: v.value)&.label || "Nil"
        v.label || "Nil"
      end
    when "MultipleChoice"
      values.map do |v|
        #v.field.field_allowed_values.find_by(uid: v.value).label
        v.label || "Nil"
      end
    else

    end

  end

  def user_field_value_badge(field_value)
    classes = ["badge", "badge-default"]
    classes = ["badge", "badge-default", "badge-#{field_value.category}".downcase]
    classes << "badge-novapass" if field_value.novapass?

    content_tag(:span, field_value.category, class: classes)
  end
end

app/views/admin/fields/index.html.erb
<% content_for :title, "Fields Admin" %>

<% content_for :breadcrumbs do %>
  <%= crumb "Admin", to: admin_path %>
  <%= crumb "Fields", active: true %>
<% end %>

<div class="table-responsive">
  <table class="table align-middle">
    <thead>
      <tr>
        <th scope="col" class="d-none d-sm-table-cell">#</th>
        <th scope="col">Name</th>
        <th scope="col">Type</th>
        <th scope="col">System Code</th>
        <th scope="col">System</th>
        <th scope="col">Editable</th>
        <th scope="col">Order</th>
      </tr>
    </thead>
    <tbody>

      <% @fields.each do |field| %>
        <tr>
          <td class="d-none d-sm-table-cell"><%= field.uid %></td>
          <td>
            <a href="<%= admin_field_path(field) %>"><%= field.field_name %></a>
          </td>
          <td><%= field.field_type %></td>
          <td><%= field.system_code %></td>
          <td><%= field.system %></td>
          <td><%= field.editable %></td>
          <td><%= field.order %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/fields/show.html.erb
<% content_for :title, "Fields Admin: #{@field.field_name}" %>

<% content_for :breadcrumbs do %>
  <%= crumb "Admin", to: admin_path %>
  <%= crumb "Fields", to: admin_fields_path %>
  <%= crumb @field.field_name, active: true %>
<% end %>

<hr>

<div class="row">
  <div class="col">
    <h2>Field Attributes</h2>
    <div class="table-responsive">
      <table class="table table-striped table-sm">
        <thead>
          <tr>
            <th scope="col">Attribute</th>
            <th scope="col">Value</th>
          </tr>
        </thead>
        <tbody>
          <% [ :id,
               :url,
               :uid,
               :access,
               :description,
               :member_access,
               :member_only,
               :built_in,
               :support_search,
               :editable,
               :admin_only,
               :field_type,
               :field_name,
               :system,
               :field_instructions,
               :max_length,
               :order,
               :display_type,
               :system_code,
               :required,
               :created_at,
               :updated_at,
          ].each do |n| %>
          <tr>
            <td><%= n.to_s %></td>
            <td scope="col"><%= @field[n] %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="col">
    <h2>Allowed Values</h2>

    <% unless @field.field_allowed_values.empty? %>
      <div class="table-responsive">
        <table class="table table-striped table-sm">
          <thead>
            <tr>
              <th scope="col">Label</th>
              <th scope="col">Value</th>
              <th scope="col">Selected by Default</th>
            </tr>
          </thead>
          <tbody>

            <% @field.field_allowed_values.each do |v| %>
              <tr>
                <td><%= v.label %></td>
                <td><%= v.value %></td>
                <td><%= v.selected_by_default %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    <% end %>
  </div>
</div>