config/routes.rb
Rails.application.routes.draw do

  namespace :wild_apricot do
    post 'webhook', to: "webhook#create"
  end

  resources :events, only: [:index, :show, :update]
  resources :waitlist, only: [:index]
  resources :waitlist_registrations, only: [:index, :create, :new]

  resources :users, only: [:index, :show, :edit, :update] do
    resource :onboarding
    resources :fields, :show, controller: "user_fields"
    patch 'sync'
  end
  resource :batch_update_tool do
    get 'search'
    get 'contact'
  end

  get 'formbot/:event', to: 'formbot#redirect', as: :formbot
  get 'signoffs', to: 'signoffs#index'

  # Admin Section
  get 'admin', to: 'admin/welcome#show'
  namespace :admin do
    resource :sync
    resources :fields, only: [:index, :show]
    resources :users, only: [:index, :show] do
      resources :fields, :show, controller: "user_fields"
    end
  end

  # Defines the root path route ("/")
  root 'welcome#index'

  # Routes for OmniAuth
  post '/auth/:provider/callback', to: 'sessions#create'
  get '/callback/:provider', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: :logout
end

app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
  <% key = "success" if key == "notice" %>
  <% key = "danger" if key == "error" %>
    <div class="alert alert-<%= key %> alert-dismissible fade show" role="alert">
    <strong><%= value %></strong>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/shared/_ga.html.erb
<% if ENV["GA_CODE"] %>
<script async src="https://www.googletagmanager.com/gtag/js?id=<%= ENV['GA_CODE'] %>"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', '<%= ENV["GA_CODE"] %>');
</script>
<% end %>

app/views/shared/_side_nav.html.erb
<div id="layoutSidenav_nav">
  <nav class="sb-sidenav accordion sb-sidenav-light" id="sidenavAccordion">
    <div class="sb-sidenav-menu">
      <div class="nav">
        <div class="sb-sidenav-menu-heading">Nova Labs</div>
        <a class="nav-link" href="<%= wa_url %>">
          <div class="sb-nav-link-icon"><i class="fas fa-lightbulb"></i></div>
          Member Portal
        </a>
        <div class="sb-sidenav-menu-heading">Resources</div>
        <a class="nav-link" href="<%= root_path %>">
          <div class="sb-nav-link-icon"><i class="fas fa-home"></i></div>
          Home
        </a>

        <a class="nav-link" href="<%= signoffs_path %>">
          <div class="sb-nav-link-icon"><i class="fas fa-screwdriver"></i></div>
          Available Sign-offs
        </a>

        <a class="nav-link" href="<%= waitlist_index_path %>">
          <div class="sb-nav-link-icon"><i class="fas fa-list"></i></div>
          Class Waitlist
        </a>

        <% if current_user %>
          <a class="nav-link" href="<%= events_path %>">
            <div class="sb-nav-link-icon"><i class="fas fa-calendar"></i></div>
            Events
          </a>

          <a class="nav-link" href="<%= users_path %>">
            <div class="sb-nav-link-icon"><i class="fas fa-users"></i></div>
            Members
          </a>

          <a class="nav-link" href="<%= adhoc_formbot_url %>">
            <div class="sb-nav-link-icon"><i class="fas fa-asterisk"></i></div>
            Ad-Hoc Class Form
          </a>

          <% if current_user&.signoffer? %>
            <div class="sb-sidenav-menu-heading text-danger">Adminstrative</div>
            <a class="nav-link text-danger" href="<%= users_path(a: :signoff) %>">
              <div class="sb-nav-link-icon text-danger"><i class="fas fa-wrench"></i></div>
              Sign-offs by Member
            </a>
            <a class="nav-link text-danger" href="<%= batch_update_tool_path %>">
              <div class="sb-nav-link-icon text-danger"><i class="fas fa-hammer"></i></div>
              Sign-offs by Tool
            </a>
            <!--
            <a class="nav-link text-danger" href="<%= waitlist_registrations_path %>">
              <div class="sb-nav-link-icon text-danger"><i class="fas fa-list"></i></div>
              Waitlist Registrations
            </a>
            -->
            <a class="nav-link text-danger" href="<%= users_path(a: :googleworkspace) %>">
              <div class="sb-nav-link-icon text-danger"><i class="fas fa-users"></i></div>
              Create Google Workspace Account
            </a>
          <% end %>
        <% end %>

        <% if false %>
          <div class="sb-sidenav-menu-heading">Super Secret Admin</div>
          <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseadmin" aria-expanded="false" aria-controls="collapseadmin">
            <div class="sb-nav-link-icon"><i class="fas fa-cog"></i></div>
            Admin
            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
          </a>
          <div class="collapse" id="collapseadmin" aria-labelledby="headingTwo" data-bs-parent="#sidenavAccordion">
            <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionadmin">
              <a class="nav-link" href="<%= admin_fields_path%>">Fields</a>
              <a class="nav-link" href="<%= admin_users_path %>">Members</a>
              <a class="nav-link" href="<%= admin_sync_path %>">Sync</a>
            </nav>
          </div>
        <% end %>
      </div>
    </div>
    <div class="sb-sidenav-footer">
      <% if current_user %>
        <div class="small">Logged in as:<br>
        <%= current_user.email %>
        </div>
      <% end %>
    </div>
  </nav>
</div>

app/views/shared/_top_nav.html.erb
<nav class="sb-topnav navbar navbar-expand navbar-dark <%= header_class %>">
  <!-- Sidebar Toggle (leftmost) -->
  <button class="btn btn-link btn-sm me-3 shadow-none" id="sidebarToggle" onClick="window.sidebarToggler(event);">
    <i class="fas fa-bars"></i>
  </button>

  <!-- Navbar Brand (just right of toggle) -->
  <a class="navbar-brand ps-2" href="/">Nova Labs Automations</a>

  <!-- Filler (disabled search box, keeps layout) -->
  <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
    <!-- optional search input could go here -->
  </form>

  <!-- User Menu (far right) -->
  <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        <i class="fas fa-user fa-fw"></i>
      </a>
      <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
        <li><a class="dropdown-item" href="#!">Settings</a></li>
        <li><a class="dropdown-item" href="#!">Activity Log</a></li>
        <li><hr class="dropdown-divider" /></li>
        <% unless current_user %>
          <li><a class="dropdown-item" href="<%= login_path %>">Sign In</a></li>
        <% else %>
          <li><a class="dropdown-item" href="<%= logout_path %>">Sign Out</a></li>
        <% end %>
      </ul>
    </li>
  </ul>
</nav>