config/routes.rb
Rails.application.routes.draw do

  namespace :wild_apricot do
    post 'webhook', to: "webhook#create"
  end

  resources :events, only: [:index, :show, :update]
  resources :waitlist, only: [:index]
  resources :waitlist_registrations, only: [:index, :create, :new]

  resources :users, only: [:index, :show, :edit, :update] do
    resource :onboarding
    resources :fields, :show, controller: "user_fields"
    patch 'sync'
  end
  resource :batch_update_tool do
    get 'search'
    get 'contact'
  end

  get 'formbot/:event', to: 'formbot#redirect', as: :formbot
  get 'signoffs', to: 'signoffs#index'

  # Admin Section
  get 'admin', to: 'admin/welcome#show'
  namespace :admin do
    resource :sync
    resources :fields, only: [:index, :show]
    resources :users, only: [:index, :show] do
      resources :fields, :show, controller: "user_fields"
    end
  end

  # Defines the root path route ("/")
  root 'welcome#index'

  # Routes for OmniAuth
  post '/auth/:provider/callback', to: 'sessions#create'
  get '/callback/:provider', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: :logout
end

app/models/user.rb
class User < ApplicationRecord
  has_one :credentials, dependent: :destroy # OAuth Credentials
  has_many :field_values, class_name: "FieldUserValue", dependent: :destroy
  has_many :event_registrations
  has_many :events, through: :event_registrations

  scope :search, ->(search_term) {
    like_term = "%#{search_term}%"

    # Use LIKE for SQLite, ILIKE for Postgres
    where(
      "email LIKE ? OR first_name LIKE ? OR last_name LIKE ?",
      like_term, like_term, like_term,
    )
  }

  scope :active_n_enabled, -> {
    where.not(membership_level_name: [nil, ""])
    .where(membership_enabled: true)
    .where(archived: false)
  }


  # {"provider"=>"wildapricot",
  #  "uid"=>"59100437",
  #  "info"=>{"email"=>"chris.sexton@nova-labs.org", "name"=>"Christopher Sexton"},
  #  "credentials"=>{"token"=>"4Vhf8e1NoRWTuv1oQcA9rV1U8Ko-", "refresh_token"=>"rt_2022-01-12_G74CM8qLVkHg5OF-nie1IxXa6Eg-", "expires_at"=>1642012132, "expires"=>true},
  #  "extra"=>
  #   {"raw_info"=>
  #     {"AdministrativeRoleTypes"=>["AccountAdministrator"],
  #      "FirstName"=>"Christopher",
  #      "LastName"=>"Sexton",
  #      "Email"=>"example@example.org",
  #      "DisplayName"=>"Sexton, Christopher",
  #      "MembershipLevel"=>
  #        {"Id"=>1264966,
  #         "Url"=>"https://api.wildapricot.org/v2/accounts/354313/MembershipLevels/1264966",
  #          "Name"=>"Key"},
  #      "Status"=>"Active",
  #      "Id"=>59100437,
  #      "Url"=>"https://api.wildapricot.org/v2/accounts/354313/Contacts/59100437",
  #      "IsAccountAdministrator"=>true,
  #      "TermsOfUseAccepted"=>true}}}
  def self.create_or_update_with_oauth(auth_hash)
    Rails.logger.info "Creating or updating user with #{auth_hash.to_json}"

    raise :unsupported unless auth_hash.provider == "wildapricot"

    user = User.find_or_create_by(provider: auth_hash.provider, uid: auth_hash.uid)
    user.email = auth_hash.info.email
    user.name = auth_hash.info.name
    user.url = auth_hash.extra.raw_info.Id
    if auth_hash.credentials
      user.credentials = Credentials.new()

      user.credentials.token = auth_hash.credentials.token
      user.credentials.refresh_token= auth_hash.credentials.refresh_token
      user.credentials.expires_at = auth_hash.credentials.expires_at
      user.credentials.expires = auth_hash.credentials.expires
    end

    user.save

    user
  end

  def signoffer?
    account_administrator? || admin || field_values.includes(:field_allowed_value).where(field_allowed_value: { label: "[NL] wautils" }).any?
  end

  def youth?
    birthdate&.after? 18.years.ago
  end

  def age
    return unless birthdate

    days = (Date.today - birthdate).to_i
    return 0 if days.negative?

    (days / 365.25).floor
  end

  def age_category
    return :adult unless birthdate.is_a?(Date)

    case age
    when 0..7
      :under_8
    when 8..11
      :age_8_to_11
    when 12..15
      :age_12_to_15
    when 16..17
      :age_16_to_17
    else
      :adult
    end
  end

  # Returns a "truple" of user value, field, and allowed field models
  def signoffs
    #values = field_values.left_joins(:field, :field_allowed_value).where(field: Field.signoffs)
    values = field_values.signoffs

    values.map do |value|
      allowed = value.field.field_allowed_values.find_by(uid: value.value)
      [value, value.field, allowed]
    end
  end

  def signoff_values
    signoffs.map {|signoff_truple| signoff_truple.first.value }
  end

  def reason_for_free_access
    field_values.find_by(field:  Field.reason_for_free_access)&.label
  end

  def door_access_group
    field_values.find_by(field:  Field.door_access_group)&.label
  end

  def has_google_workspace_account?
    !!(email =~ /nova-labs.org$/ || secondary_email =~ /nova-labs.org$/)
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  def index
    @users = User.all
  end

  def show
    @user = User.find params[:id]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_signoffer, only: [:edit, :update]
  def index
    @users = User.active_n_enabled.order("LOWER(last_name)").page(params[:page])

    if params[:q]
      @users = @users.search(params[:q])
    end
  end

  def show
    @user = User.find(params[:id])
    @signoffs = @user.field_values.signoffs
    @door_access_group = @user.field_values.door_access_group
  end

  def edit
    @user = User.find(params[:id])
    @signoffs = @user.field_values.signoffs
    @signoffs = @user.field_values.signoffs
  end

  def update
    raise "not implmented"
  end

  def sync
    @user = User.find(params[:user_id])
    ret = WAAPI.contact(@user.uid)

    if ret.status == 404 # Deleted
      @user.delete
      redirect_to users_path, notice: "Successful sync from portal, this user was deleted"
    else
      WildApricotSync.new.contact(ret.json)
      redirect_to user_path(@user), notice: "Successful sync from portal (#{ret.status})"
    end
  end
end

app/helpers/user_helper.rb
# frozen_string_literal: true

module UserHelper
  def gravatar_url(user, size=200)
    gravatar_id = Digest::MD5.hexdigest(user.email)
    "https://gravatar.com/avatar/#{gravatar_id}.png?d=mp&s=#{size}"
  end

  def youth_badge(user)
    case user.age_category
    when :under_8
      content_tag(:span, "Youth under 8", class: "badge bg-warning text-dark", title: "Youth age 7 and under")
    when :age_8_to_11
      content_tag(:span, "Youth 8–11", class: "badge bg-warning text-dark", title: "Youth age 8 to 11")
    when :age_12_to_15
      content_tag(:span, "Youth 12–15", class: "badge bg-warning text-dark", title: "Youth age 12 to 15")
    when :age_16_to_17
      content_tag(:span, "Youth 16–17", class: "badge bg-warning text-dark", title: "Youth age 16 to 17")
    else
      ""
    end
  end


  def youth_access_details(user)
    case user.age_category
    when :under_8
      "Youth under 12 are not allowed access to tools"
    when :age_8_to_11
      "Youth under 12 are not allowed access to tools"
    when :age_12_to_15
      "Youth age 12 to 15"
    when :age_16_to_17
      "Youth age 16 to 17"
    else
      ""
    end
  end
end

app/views/admin/users/index.html.erb
<% content_for :title, "Members Admin" %>

<% content_for :breadcrumbs do %>
  <%= crumb "Admin", to: admin_path %>
  <%= crumb "Members", active: true %>
<% end %>

<div class="table-responsive">
  <table class="table align-middle">
    <thead>
      <tr>
        <th scope="col" class="d-none d-sm-table-cell">#</th>
        <th scope="col">Name</th>
        <th scope="col">email</th>
        <th scope="col">Admin</th>
        <th scope="col">Account Administrator</th>
        <th scope="col">Membership</th>
      </tr>
    </thead>
    <tbody>

      <% @users.each do |user| %>
        <tr>
          <td class="d-none d-sm-table-cell"><%= user.uid %></td>
          <td><a href="<%= admin_user_path(user) %>"><%= user.name %></a></td>
          <td><%= user.email %></td>
          <td><%= user.admin %></td>
          <td><%= user.account_administrator %></td>
          <td><%= user.membership_level_name %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/users/show.html.erb
<% content_for :title, "Members Admin: #{@user.name}" %>

<% content_for :breadcrumbs do %>
  <%= crumb "Admin", to: admin_path %>
  <%= crumb "Members", to: admin_users_path %>
  <%= crumb @user.name, active: true %>
<% end %>


<div class="row">
  <div class="col col-md-6">
    <h2>Attributes</h2>
    <div class="table-responsive">
      <table class="table table-striped table-sm">
        <thead>
          <tr>
            <th scope="col">Attribute</th>
            <th scope="col">Value</th>
          </tr>
        </thead>
        <tbody>
          <% [ :id,
               :account_administrator,
               :admin,
               :membership_enabled,
               :membership_level_id,
               :membership_level_name,
               :membership_level_url,
               :email,
               :first_name,
               :last_name,
               :name,
               :provider,
               :status,
               :uid,
               :url,
               :created_at,
               :updated_at,
          ].each do |n| %>
          <tr>
            <td><%= n.to_s %></td>
            <td scope="col"><%= @user[n] %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <div class="col col-md-6">

    <h2>Fields</h2>

    <div class="table-responsive">
      <table class="table table-striped table-sm">
        <thead>
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Type</th>
            <th scope="col">Value</th>
          </tr>
        </thead>
        <tbody>

          <% @user.field_values.group_by(&:system_code).each do |k,v| %>
            <% field = Field.find_by system_code: k %>
            <tr>
              <td>
                <% if ["String", "Choice", "MultipleChoice"].include? field.field_type %>
                  <%= link_to field.field_name, edit_admin_user_field_path(@user, field) %>
                <% else %>
                  <%= field.field_name %>
                <% end %>
              </td>
              <td><%= field.field_type%></td>
              <td>
                <%= print_field_user_values(v).join(", ") %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>


  </div>
</div>